# Clustering

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import scipy
from sklearn.neighbors import KNeighborsClassifier

# чтоб картинки рисовались в тетрадке
%matplotlib inline

In [3]:
data = pd.read_csv('adult_data.csv')
data = data.sample(100, random_state=123)
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
20713,55,State-gov,199713,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,15,United-States,<=50K
13495,65,Private,115890,Bachelors,13,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,20,United-States,<=50K
12367,29,Private,145592,HS-grad,9,Never-married,Craft-repair,Not-in-family,White,Male,0,0,40,Guatemala,<=50K
22402,53,State-gov,231472,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,>50K
18338,32,Private,107218,Bachelors,13,Never-married,Adm-clerical,Not-in-family,Asian-Pac-Islander,Male,0,0,40,United-States,<=50K

In [4]:
avail = [col for col, typ in zip(data.columns, data.dtypes) if '64' in str(typ)]

data = data[avail]

In [5]:
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = pd.DataFrame(MinMaxScaler().fit_transform(data), columns=data.columns)
data

,age,fnlwgt,education-num,capital-gain,capital-loss,hours-per-week
0,0.584615,0.349736,0.800000,0.000000,0.000000,0.125000
1,0.738462,0.184314,0.800000,0.000000,0.000000,0.177083
2,0.184615,0.242930,0.533333,0.000000,0.000000,0.385417
3,0.553846,0.412412,1.000000,0.000000,0.000000,0.385417
4,0.230769,0.167200,0.800000,0.000000,0.000000,0.385417
...,...,...,...,...,...,...
95,0.123077,0.393239,0.533333,0.000000,0.000000,0.385417
96,0.615385,0.293550,0.400000,0.000000,0.000000,0.385417
97,0.230769,0.340435,0.533333,0.000000,0.000000,0.385417
98,0.415385,0.285188,0.800000,0.076881,0.000000,0.593750
99,0.200000,0.753012,0.533333,0.000000,0.818634,0.125000

In [11]:
db = DBSCAN(eps=0.3, min_samples=3)
db.fit_predict(data)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,
        1, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
       -1,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  1, -1,  0,  0,  0,  0,
        0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1],
      dtype=int32)

In [12]:
db.components_

array([[0.58461538, 0.34973615, 0.8       , 0.        , 0.        ,
        0.125     ],
       [0.73846154, 0.18431408, 0.8       , 0.        , 0.        ,
        0.17708333],
       [0.18461538, 0.24293005, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.55384615, 0.41241154, 1.        , 0.        , 0.        ,
        0.38541667],
       [0.23076923, 0.16720016, 0.8       , 0.        , 0.        ,
        0.38541667],
       [0.32307692, 0.12084141, 0.53333333, 0.        , 0.        ,
        0.46875   ],
       [0.23076923, 0.46058983, 0.8       , 0.        , 0.        ,
        0.41666667],
       [0.27692308, 0.23282984, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.53846154, 0.14306464, 0.13333333, 0.        , 0.        ,
        0.48958333],
       [0.29230769, 0.30303796, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.13846154, 0.47502575, 0.6       , 0.        , 0.        ,
        0.36458333],
       [0.30769231, 0.07446489, 0.8       , 0.        , 0.        ,
        0.36458333],
       [0.13846154, 0.23794901, 0.6       , 0.02407024, 0.        ,
        0.48958333],
       [0.16923077, 0.3352726 , 0.8       , 0.        , 0.        ,
        0.38541667],
       [0.47692308, 0.43640695, 0.6       , 0.07688077, 0.        ,
        0.38541667],
       [0.16923077, 0.18389373, 0.73333333, 0.        , 0.        ,
        0.30208333],
       [0.07692308, 0.19344729, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.46153846, 0.31771267, 0.8       , 0.        , 0.        ,
        0.48958333],
       [0.63076923, 0.35295487, 0.8       , 0.        , 0.        ,
        0.17708333],
       [0.32307692, 0.01662055, 0.73333333, 0.        , 0.        ,
        0.59375   ],
       [0.32307692, 0.21504296, 0.26666667, 0.        , 0.        ,
        0.21875   ],
       [0.6       , 0.45960507, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.53846154, 0.10305059, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.47692308, 0.29641697, 0.66666667, 0.        , 0.        ,
        0.38541667],
       [0.49230769, 0.00437715, 0.8       , 0.        , 0.        ,
        0.33333333],
       [0.38461538, 0.22674366, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.36923077, 0.20320215, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.24615385, 0.17925411, 0.6       , 0.        , 0.        ,
        0.48958333],
       [0.43076923, 0.62595861, 0.86666667, 0.01506015, 0.        ,
        0.4375    ],
       [0.27692308, 0.04975707, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.43076923, 0.29983304, 0.6       , 0.        , 0.        ,
        0.33333333],
       [0.33846154, 0.38875162, 0.8       , 0.0501305 , 0.        ,
        0.30208333],
       [0.81538462, 0.32713401, 0.53333333, 0.        , 0.        ,
        0.13541667],
       [0.56923077, 0.24195515, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.83076923, 0.31555962, 0.8       , 0.11678117, 0.        ,
        0.4375    ],
       [0.29230769, 0.3414535 , 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.13846154, 0.16981303, 0.53333333, 0.        , 0.        ,
        0.33333333],
       [0.46153846, 0.3187369 , 0.53333333, 0.03325033, 0.        ,
        0.4375    ],
       [0.50769231, 0.29826216, 0.53333333, 0.        , 0.        ,
        0.59375   ],
       [0.27692308, 0.38054199, 0.66666667, 0.        , 0.        ,
        0.33333333],
       [0.38461538, 0.35427118, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.61538462, 0.05407107, 0.86666667, 0.        , 0.        ,
        0.59375   ],
       [0.27692308, 0.11866073, 0.6       , 0.        , 0.        ,
        0.80208333],
       [0.21538462, 0.23676888, 0.8       , 0.        , 0.        ,
        0.38541667],
       [0.69230769, 0.35435998, 0.8       , 0.14084141, 0.        ,
        0.38541667],
       [0.38461538, 0.30686451, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.16923077, 0.17071886, 0.86666667, 0.        , 0.        ,
        0.36458333],
       [0.43076923, 0.28218629, 1.        , 0.        , 0.        ,
        0.48958333],
       [0.38461538, 0.39753553, 0.73333333, 0.        , 0.        ,
        0.38541667],
       [0.21538462, 0.29799575, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.41538462, 0.06658878, 0.6       , 0.02202022, 0.        ,
        0.4375    ],
       [0.01538462, 0.40349935, 0.53333333, 0.        , 0.        ,
        0.28125   ],
       [0.75384615, 0.28411437, 0.4       , 0.        , 0.        ,
        0.23958333],
       [0.26153846, 0.36543509, 0.6       , 0.        , 0.78136646,
        0.38541667],
       [0.13846154, 0.38929827, 0.53333333, 0.        , 0.        ,
        0.13541667],
       [0.35384615, 0.3472476 , 0.4       , 0.        , 0.        ,
        0.38541667],
       [0.12307692, 0.30006789, 0.53333333, 0.        , 0.        ,
        0.44791667],
       [0.46153846, 0.01745533, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.32307692, 0.        , 0.6       , 0.07443074, 0.        ,
        0.38541667],
       [0.8       , 0.27864391, 0.6       , 0.        , 0.        ,
        0.13541667],
       [0.18461538, 0.02474335, 0.6       , 0.        , 0.        ,
        0.59375   ],
       [0.15384615, 0.26667482, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.09230769, 0.25297698, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.04615385, 0.32782867, 0.6       , 0.        , 0.        ,
        0.36458333],
       [0.64615385, 0.29038605, 0.73333333, 0.        , 0.        ,
        0.38541667],
       [0.55384615, 0.14411255, 0.53333333, 0.        , 0.        ,
        0.40625   ],
       [0.16923077, 0.26621501, 0.8       , 0.        , 0.        ,
        0.38541667],
       [0.46153846, 0.27521205, 0.53333333, 0.        , 0.        ,
        0.30208333],
       [0.61538462, 0.22061801, 0.6       , 0.        , 0.        ,
        0.33333333],
       [0.10769231, 0.51007456, 0.53333333, 0.        , 0.        ,
        0.21875   ],
       [0.12307692, 0.28022071, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.36923077, 0.37987496, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.52307692, 0.44839577, 0.6       , 0.        , 0.        ,
        0.38541667],
       [0.50769231, 0.16183825, 0.86666667, 0.        , 0.        ,
        0.38541667],
       [0.53846154, 0.17153192, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.35384615, 0.04187109, 0.53333333, 0.        , 0.        ,
        0.4375    ],
       [0.29230769, 0.22680484, 0.66666667, 0.        , 0.        ,
        0.35416667],
       [0.50769231, 0.29346466, 0.4       , 0.        , 0.        ,
        0.38541667],
       [0.49230769, 0.34353551, 0.8       , 0.        , 0.        ,
        0.4375    ],
       [0.38461538, 0.38896476, 0.8       , 0.        , 0.        ,
        0.54166667],
       [0.43076923, 0.38573222, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.38461538, 0.2569101 , 0.2       , 0.        , 0.        ,
        0.38541667],
       [0.32307692, 0.16736593, 0.6       , 0.        , 0.        ,
        0.59375   ],
       [0.12307692, 0.39323929, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.61538462, 0.29354952, 0.4       , 0.        , 0.        ,
        0.38541667],
       [0.23076923, 0.34043519, 0.53333333, 0.        , 0.        ,
        0.38541667],
       [0.41538462, 0.28518793, 0.8       , 0.07688077, 0.        ,
        0.59375   ]])

In [13]:
pd.DataFrame(db.components_)

           0         1         2         3    4         5
0   0.584615  0.349736  0.800000  0.000000  0.0  0.125000
1   0.738462  0.184314  0.800000  0.000000  0.0  0.177083
2   0.184615  0.242930  0.533333  0.000000  0.0  0.385417
3   0.553846  0.412412  1.000000  0.000000  0.0  0.385417
4   0.230769  0.167200  0.800000  0.000000  0.0  0.385417
..       ...       ...       ...       ...  ...       ...
82  0.323077  0.167366  0.600000  0.000000  0.0  0.593750
83  0.123077  0.393239  0.533333  0.000000  0.0  0.385417
84  0.615385  0.293550  0.400000  0.000000  0.0  0.385417
85  0.230769  0.340435  0.533333  0.000000  0.0  0.385417
86  0.415385  0.285188  0.800000  0.076881  0.0  0.593750

[87 rows x 6 columns]

In [18]:
print(db.components_[0])
print(db.components_[1])

[0.58461538 0.34973615 0.8        0.         0.         0.125     ]
[0.73846154 0.18431408 0.8        0.         0.         0.17708333]

In [25]:
from scipy.spatial import distance

In [26]:
distance.pdist(db.components_)

array([0.23183134, 0.55707764, 0.33569598, ..., 0.40976217, 0.49938297,
       0.39693783])

In [27]:
distance.cdist(db.components_, db.components_)

array([[0.        , 0.23183134, 0.55707764, ..., 0.48158127, 0.51402486,
        0.50837264],
       [0.23183134, 0.        , 0.65168649, ..., 0.48008654, 0.62979296,
        0.54228774],
       [0.55707764, 0.65168649, 0.        , ..., 0.45376452, 0.10787692,
        0.41888508],
       ...,
       [0.48158127, 0.48008654, 0.45376452, ..., 0.        , 0.40976217,
        0.49938297],
       [0.51402486, 0.62979296, 0.10787692, ..., 0.40976217, 0.        ,
        0.39693783],
       [0.50837264, 0.54228774, 0.41888508, ..., 0.49938297, 0.39693783,
        0.        ]])

In [28]:
distance.cdist(db.components_, db.components_)[0][1]

0.23183134494871172

In [29]:
distance.euclidean(db.components_[0], db.components_[1])

0.23183134494871172